/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projetolocadoradeswing;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuário
 */
public class RemoverFilme extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverFilme
     */
    public RemoverFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneRemover = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        deletarFilme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BotaoApagar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Apagar Filme");

        jLabel1.setText("Informe o filme para deletar");

        deletarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarFilmeActionPerformed(evt);
            }
        });

        jLabel2.setText("Filme para ser deletado");

        BotaoApagar.setText("Apagar");
        BotaoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        paneRemover.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneRemover.setLayer(deletarFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneRemover.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneRemover.setLayer(BotaoApagar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneRemover.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneRemover.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneRemoverLayout = new javax.swing.GroupLayout(paneRemover);
        paneRemover.setLayout(paneRemoverLayout);
        paneRemoverLayout.setHorizontalGroup(
            paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverLayout.createSequentialGroup()
                .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneRemoverLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(paneRemoverLayout.createSequentialGroup()
                                .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotaoApagar)
                                    .addComponent(jLabel2))
                                .addGap(55, 55, 55)
                                .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deletarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)))))
                    .addGroup(paneRemoverLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton3)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        paneRemoverLayout.setVerticalGroup(
            paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(paneRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoApagar)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneRemover))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneRemover)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarActionPerformed
        Filmes filme = new Filmes();
        filme.setId(Integer.parseInt(deletarFilme.getText()));

        FilmesDAO dao = new FilmesDAO();
        dao.apagarFilme(filme);
        JOptionPane.showMessageDialog(null, "Filme "+deletarFilme.getText()+" DELETADO com sucesso! ");

    }//GEN-LAST:event_BotaoApagarActionPerformed

    private void deletarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarFilmeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deletarFilme.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoApagar;
    private javax.swing.JTextField deletarFilme;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDesktopPane paneRemover;
    // End of variables declaration//GEN-END:variables
}
